services:
  - type: web
    name: ufx-backend
    env: node
    plan: standard
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start

cronJobs:
  - name: geipan-auto-import
    schedule: "0 1 * * *"
    command: >
      curl -s -X POST
      "https://ufx-backend.onrender.com/api/import/geipan-auto?cron_token=ufx2025secure!"
